version: "3"
services:
  app:
    build: .docker/app
    volumes:
      - .:/work
      - ./.docker/app/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/app/supervisord.conf:/etc/supervisord.conf
    command: supervisord
    ports:
      - 8000:80
    links:
      - db
      - redis
      - mail

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    volumes:
      - ./volumes/db:/var/lib/mysql
    ports:
      - 13306:3306

  db-testing:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=homestead_testing
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    ports:
      - 23306:23306

  redis:
    image: redis:alpine

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025
